# Generated by Django 4.2.4 on 2023-08-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametype',
            name='label',
            field=models.CharField(default='Default Label', max_length=100),
        ),
    ]
