# Generated by Django 4.2.4 on 2023-08-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_event_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players_needed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='skill_level',
            field=models.CharField(default=1, max_length=15),
        ),
    ]
