# Generated by Django 4.2.4 on 2023-09-06 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_game_players_needed_game_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='gamer',
        ),
    ]
